// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmURWNGTLvtZFsrVqBMlpJlBmHJ3faEb0',
    appId: '1:953596605550:web:10855c421b82228dde627f',
    messagingSenderId: '953596605550',
    projectId: 'spotify1612',
    authDomain: 'spotify1612.firebaseapp.com',
    storageBucket: 'spotify1612.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBza8QxT71Q_WeLNf81VVpLhQZAnDslbg8',
    appId: '1:953596605550:android:741a273f5cd351dcde627f',
    messagingSenderId: '953596605550',
    projectId: 'spotify1612',
    storageBucket: 'spotify1612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuxcsBJnUPR17rtGy2tz7eKmGsZfh88cI',
    appId: '1:953596605550:ios:00bd9d3d90ed8a9bde627f',
    messagingSenderId: '953596605550',
    projectId: 'spotify1612',
    storageBucket: 'spotify1612.firebasestorage.app',
    iosBundleId: 'com.example.dart01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuxcsBJnUPR17rtGy2tz7eKmGsZfh88cI',
    appId: '1:953596605550:ios:00bd9d3d90ed8a9bde627f',
    messagingSenderId: '953596605550',
    projectId: 'spotify1612',
    storageBucket: 'spotify1612.firebasestorage.app',
    iosBundleId: 'com.example.dart01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmURWNGTLvtZFsrVqBMlpJlBmHJ3faEb0',
    appId: '1:953596605550:web:9fc673574b7b1603de627f',
    messagingSenderId: '953596605550',
    projectId: 'spotify1612',
    authDomain: 'spotify1612.firebaseapp.com',
    storageBucket: 'spotify1612.firebasestorage.app',
  );
}
